[core]
dcos_url = "http://dcos.company.com"
timeout = 5
ssl_verify = "false"
email = "dcoscli@mesosphere.io"
reporting = false
[package]
sources = [ "https://github.com/mesosphere/multiverse/archive/version-1.x.zip", "https://github.com/mesosphere/universe/archive/version-1.x.zip",]
cache = "/home/dcoscli/.dcos/cache"
